using FluentMigrator;

namespace Discovery.Migrations.Migrations;

[Migration(20260429_111)]
public class M111_CreateReportSchedules : Migration
{
    public override void Up()
    {
        Create.Table("report_schedules")
            .WithColumn("id").AsGuid().PrimaryKey()
            .WithColumn("template_id").AsGuid().NotNullable()
                .ForeignKey("fk_report_schedule_template", "report_templates", "id")
            .WithColumn("client_id").AsGuid().Nullable()
                .ForeignKey("fk_report_schedule_client", "clients", "id")
            .WithColumn("format").AsInt32().NotNullable().WithDefaultValue(1)
            .WithColumn("filters_json").AsString(int.MaxValue).Nullable()
            .WithColumn("schedule_label").AsString(300).Nullable()
            .WithColumn("cron_expression").AsString(200).NotNullable().WithDefaultValue("0 8 * * 1")
            .WithColumn("time_zone_id").AsString(100).NotNullable().WithDefaultValue("UTC")
            .WithColumn("max_retained_executions").AsInt32().NotNullable().WithDefaultValue(10)
            .WithColumn("is_active").AsBoolean().NotNullable().WithDefaultValue(true)
            .WithColumn("next_trigger_at").AsCustom("timestamptz").Nullable()
            .WithColumn("last_triggered_at").AsCustom("timestamptz").Nullable()
            .WithColumn("created_at").AsCustom("timestamptz").NotNullable().WithDefault(SystemMethods.CurrentUTCDateTime)
            .WithColumn("updated_at").AsCustom("timestamptz").NotNullable().WithDefault(SystemMethods.CurrentUTCDateTime)
            .WithColumn("created_by").AsString(200).Nullable()
            .WithColumn("updated_by").AsString(200).Nullable();

        Create.Index("ix_report_schedules_template_id").OnTable("report_schedules").OnColumn("template_id");
        Create.Index("ix_report_schedules_client_id").OnTable("report_schedules").OnColumn("client_id");
        Create.Index("ix_report_schedules_next_trigger_at").OnTable("report_schedules").OnColumn("next_trigger_at");
        Create.Index("ix_report_schedules_is_active").OnTable("report_schedules").OnColumn("is_active");

        // Track which executions were generated by which schedule
        Alter.Table("report_executions")
            .AddColumn("schedule_id").AsGuid().Nullable()
                .ForeignKey("fk_report_exec_schedule", "report_schedules", "id");
        Create.Index("ix_report_executions_schedule_id").OnTable("report_executions").OnColumn("schedule_id");
    }

    public override void Down()
    {
        Delete.Column("schedule_id").FromTable("report_executions");
        Delete.Table("report_schedules");
    }
}
