using Discovery.Core.Cqrs;
namespace Discovery.Core.Cqrs.Automation.Queries;
public sealed record ListScriptsQuery(string? Search, string? Cursor, int Limit = 50) : IQuery<Result<ListScriptsResult>>;
public sealed record ListScriptsResult(IReadOnlyList<ScriptDto> Items, string? NextCursor, bool HasMore);
public sealed record ScriptDto(Guid Id, string Name, string? Description, string Type, DateTime CreatedAt);
public sealed record GetScriptByIdQuery(Guid Id) : IQuery<Result<ScriptDetailDto>>;
public sealed record ScriptDetailDto(Guid Id, string Name, string Description, string Type, string Content, DateTime CreatedAt);
public sealed record ListTasksQuery(Guid? ScriptId, string? Status, string? Cursor, int Limit = 50) : IQuery<Result<ListTasksResult>>;
public sealed record ListTasksResult(IReadOnlyList<TaskDto> Items, string? NextCursor, bool HasMore);
public sealed record TaskDto(Guid Id, string Name, string Status, Guid? ScriptId, DateTime CreatedAt);
public sealed record ListAutoTicketRulesQuery(Guid? ClientId, Guid? SiteId) : IQuery<Result<List<AutoTicketRuleDto>>>;
public sealed record AutoTicketRuleDto(Guid Id, string Name, bool Enabled, Guid? ClientId, DateTime CreatedAt);
