using Discovery.Core.DTOs;

namespace Discovery.Core.Interfaces;

public interface IAgentPackageService
{
    /// <summary>
    /// Ensures the base Discovery binary exists by running a no-package Wails build.
    /// This is intended to run at API startup to reduce installer build latency.
    /// </summary>
    Task PrebuildBaseBinaryAsync(bool forceRebuild = false, CancellationToken cancellationToken = default);

    /// <summary>
    /// Builds a ZIP package in memory containing the agent binary and a
    /// pre-configured debug_config.json with the given deploy token and server URLs.
    /// </summary>
    Task<byte[]> BuildPortablePackageAsync(string rawDeployToken, string? publicApiBaseUrl = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Builds a NSIS installer executable with defaults embedded at build time.
    /// The deploy token is embedded as ARG_DEFAULT_KEY.
    /// This produces the FULL stage2 installer (the payload that the bootstrap downloads).
    /// </summary>
    Task<(byte[] Content, string FileName)> BuildInstallerAsync(string rawDeployToken, string? publicApiBaseUrl = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Builds a bootstrap (minimal) NSIS installer that downloads and executes the stage2
    /// from the public download endpoint (/api/v1/download/agent).
    /// The deploy token and server URL are embedded so the stage2 receives them at runtime.
    /// Requires a current stage2 build to exist (published via refresh-build).
    /// </summary>
    /// <param name="rawDeployToken">Deploy token to embed in bootstrap defaults.</param>
    /// <param name="publicApiBaseUrl">Public API base URL used to construct the stage2 download URL.</param>
    Task<(byte[] Content, string FileName)> BuildBootstrapInstallerAsync(string rawDeployToken, string? publicApiBaseUrl = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Builds a generic (zero-touch) NSIS installer with no URL or deploy token embedded.
    /// The agent starts in P2P auto-provisioning mode — it discovers the server via
    /// peer discovery and self-registers. No API endpoint or token is needed at install time.
    /// Result is cached in memory with a configurable TTL.
    /// </summary>
    Task<(byte[] Content, string FileName)> BuildGenericInstallerAsync(bool forceRebuild = false, CancellationToken cancellationToken = default);

    /// <summary>
    /// Builds a NSIS installer executable for agent self-update flow.
    /// This variant does not embed bootstrap defaults (URL/token/discovery/minimal)
    /// so an existing agent configuration is preserved during /S /UPDATE runs.
    /// </summary>
    Task<(byte[] Content, string FileName)> BuildUpdateInstallerAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Resolves the short commit hash of the agent source repository at build time.
    /// Uses a 3-level fallback:
    /// 1. Read agent-version.json from build output (generated by the agent build script)
    /// 2. Run git rev-parse --short=8 HEAD in the configured DiscoveryProjectPath
    /// 3. Return "unknown"
    /// </summary>
    Task<string> GetAgentCommitHashAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Synchronizes the agent source repository with the configured branch.
    /// Executes git fetch + git reset --hard to the target branch on origin.
    /// Only allows branches from the configured safe list (dev, release, beta, lts).
    /// Returns sync result with before/after commit hashes.
    /// </summary>
    Task<AgentRepositorySyncResult> SyncRepositoryAsync(string branch, CancellationToken cancellationToken = default);
}
